#!/bin/bash

set -e

PROJECT_ROOT=$(cd "$(dirname "$0")/.." && pwd)
source "$PROJECT_ROOT/config/runtime.sh"
load_runtime_config

: "${NEXUS_PROXY_CONNECT_TIMEOUT_SECONDS:=60}"
: "${NEXUS_PROXY_SEND_TIMEOUT_SECONDS:=60}"
: "${NEXUS_PROXY_READ_TIMEOUT_SECONDS:=60}"
: "${NEXUS_WEBSOCKET_READ_TIMEOUT_SECONDS:=86400}"
: "${NEXUS_STATIC_CACHE_DAYS:=365}"
: "${NEXUS_NGINX_HTTP_PORT:=80}"
: "${NEXUS_NGINX_HTTPS_PORT:=443}"
: "${NEXUS_TLS_SERVER_NAME:=nexus.local}"

TEMPLATE_PATH=${1:-"$PROJECT_ROOT/deploy/nginx-nexus.conf"}
OUTPUT_PATH=${2:-"/tmp/$(basename "$TEMPLATE_PATH").rendered"}

export NEXUS_PUBLIC_HOST
export NEXUS_BACKEND_PORT
export NEXUS_HSTS_MAX_AGE_SECONDS
export NEXUS_PROXY_CONNECT_TIMEOUT_SECONDS
export NEXUS_PROXY_SEND_TIMEOUT_SECONDS
export NEXUS_PROXY_READ_TIMEOUT_SECONDS
export NEXUS_WEBSOCKET_READ_TIMEOUT_SECONDS
export NEXUS_STATIC_CACHE_DAYS
export NEXUS_NGINX_HTTP_PORT
export NEXUS_NGINX_HTTPS_PORT
export NEXUS_TLS_SERVER_NAME

envsubst \
    '${NEXUS_PUBLIC_HOST} ${NEXUS_BACKEND_PORT} ${NEXUS_HSTS_MAX_AGE_SECONDS} ${NEXUS_PROXY_CONNECT_TIMEOUT_SECONDS} ${NEXUS_PROXY_SEND_TIMEOUT_SECONDS} ${NEXUS_PROXY_READ_TIMEOUT_SECONDS} ${NEXUS_WEBSOCKET_READ_TIMEOUT_SECONDS} ${NEXUS_STATIC_CACHE_DAYS} ${NEXUS_NGINX_HTTP_PORT} ${NEXUS_NGINX_HTTPS_PORT} ${NEXUS_TLS_SERVER_NAME}' \
    < "$TEMPLATE_PATH" > "$OUTPUT_PATH"

echo "Rendered: $OUTPUT_PATH"
