#!/bin/bash

PROJECT_ROOT=$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)

load_runtime_config() {
    if [ -f "$PROJECT_ROOT/.env" ]; then
        set -a
        source "$PROJECT_ROOT/.env" 2>/dev/null || true
        set +a
    fi

    : "${NEXUS_HOST:=0.0.0.0}"
    : "${NEXUS_BACKEND_PORT:=${NEXUS_PORT:-18890}}"
    : "${NEXUS_DEV_BACKEND_PORT:=8000}"
    : "${NEXUS_FRONTEND_PORT:=3000}"
    : "${NEXUS_PUBLIC_HOST:=107.174.231.22}"
    : "${NEXUS_PUBLIC_PORT:=8888}"
    : "${NEXUS_CADDY_ADMIN_HOST:=localhost}"
    : "${NEXUS_CADDY_ADMIN_PORT:=2018}"
    : "${NEXUS_PROCESS_STOP_WAIT_SECONDS:=2}"
    : "${NEXUS_HEALTHCHECK_WAIT_SECONDS:=5}"
    : "${NEXUS_STACK_READY_WAIT_SECONDS:=6}"
    : "${NEXUS_PLAYWRIGHT_CHECK_ENABLED:=1}"
    : "${NEXUS_PLAYWRIGHT_TIMEOUT_MS:=30000}"
    : "${NEXUS_PLAYWRIGHT_HYDRATION_WAIT_MS:=4000}"

    NEXUS_PUBLIC_URL="http://${NEXUS_PUBLIC_HOST}:${NEXUS_PUBLIC_PORT}"
    NEXUS_BACKEND_URL="http://127.0.0.1:${NEXUS_BACKEND_PORT}"
    NEXUS_FRONTEND_URL="http://127.0.0.1:${NEXUS_FRONTEND_PORT}"
    NEXUS_DEV_API_URL="http://localhost:${NEXUS_DEV_BACKEND_PORT}"

    export NEXUS_HOST
    export NEXUS_BACKEND_PORT
    export NEXUS_DEV_BACKEND_PORT
    export NEXUS_FRONTEND_PORT
    export NEXUS_PUBLIC_HOST
    export NEXUS_PUBLIC_PORT
    export NEXUS_CADDY_ADMIN_HOST
    export NEXUS_CADDY_ADMIN_PORT
    export NEXUS_PROCESS_STOP_WAIT_SECONDS
    export NEXUS_HEALTHCHECK_WAIT_SECONDS
    export NEXUS_STACK_READY_WAIT_SECONDS
    export NEXUS_PLAYWRIGHT_CHECK_ENABLED
    export NEXUS_PLAYWRIGHT_TIMEOUT_MS
    export NEXUS_PLAYWRIGHT_HYDRATION_WAIT_MS
    export NEXUS_PUBLIC_URL
    export NEXUS_BACKEND_URL
    export NEXUS_FRONTEND_URL
    export NEXUS_DEV_API_URL
}
